logging:
  level:
    ROOT: DEBUG
    tech.jhipster: DEBUG
    org.hibernate.SQL: DEBUG
    com.vitamiel: DEBUG
    com.paypal: DEBUG  

spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**,.h2.server.properties
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:./h2db/db/ecomvitamiel;DB_CLOSE_DELAY=-1
    username: ecomvitamiel
    password:
    hikari:
      poolName: Hikari
      auto-commit: false
  data:
    mongodb:
      uri: mongodb://localhost:27017/vatamiel # Replace with your MongoDB URI
  h2:
    console:
      # disable spring boot built-in h2-console since we start it manually with correct configuration
      enabled: false
  liquibase:
    # Remove 'faker' if you do not want the sample data to be loaded automatically
    contexts: dev, faker
  mail:
    host: smtp.gmail.com
    port: 25
    username: vitamiel.be@gmail.com
    password: Faramir**11Amir!!
  messages:
    cache-duration: PT1S # 1 second, see the ISO 8601 standard
  thymeleaf:
    cache: false
  file:
  upload-dir: ${USER_HOME}/uploads  # Use a user directory or other absolute path

server:
  port: 8080
  # make sure requests the proxy uri instead of the server one
  forward-headers-strategy: native

jhipster:
  # CORS is only enabled by default with  "dev" profile
  cors:
    # Allow Ionic for JHipster by default (* no longer allowed in Spring Boot 2.4+)
    allowed-origins: 'http://localhost:8100,https://localhost:8100,http://localhost:9000,https://localhost:9000,http://localhost:9060,https://localhost:9060'
    # Enable CORS when running in GitHub Codespaces
    allowed-origin-patterns: 'https://*.githubpreview.dev'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count,X-${jhipster.clientApp.name}-alert,X-${jhipster.clientApp.name}-error,X-${jhipster.clientApp.name}-params'
    allow-credentials: true
    max-age: 1800
  security:
    authentication:
      jwt:
        # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
        base64-secret: NmFjY2ZmZTQ0ZTZkYzRjZTRjMWI3NjIyZjIzYWZiMWQxZmY4M2I4ZjEzOGFiMjM3MGFlYTgwY2I2NGM2ZTQwZDc5OGI0M2Q2NzhkYzNmOTE0YmIyN2RkNGMyNjE1OWM1YjQ3NjFkNTQ2Y2UzNGQ4NDc2MDExYTM4YTA2YWY4YmE=
        # Token is valid 24 hours
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
  mail: # specific JHipster mail property, for standard properties see MailProperties
    base-url: http://127.0.0.1:8080
  logging:
    use-json-format: false # By default, logs are not in Json format
    logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
      enabled: false
      host: localhost
      port: 5000
      ring-buffer-size: 512
# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the JHipsterProperties above
#
# More documentation is available at:
# https://www.jhipster.tech/common-application-properties/
# ===================================================================

# application:

# PayPal Configuration
paypal:
  client:
    id: ASZqYCLb4pjpMt3Bq2RsQtrtgXYCA9Ido09Za0_GX7bCr5tth3Q4YEMJ9Bp33aL8ACCeaDRnrPjueGQW
    secret: EC_nlQdVsaTSYOuOGPB-xzLTOT3Ax0Hf_5BXkSUtaUQUw53ylaF-gxpOl15wAmARQL6hyzzshIrrEiqU  
  mode: sandbox  
  redirect:
    return-url: http://localhost:8080/paypal/return  # URL for successful payment
    cancel-url: http://localhost:8080/paypal/cancel  # URL for canceled payment